name: Release Dev Container Features

on:
  workflow_dispatch:

jobs:
  ci:
    permissions:
      contents: read
    uses: ./.github/workflows/ci.yml

  validate:
    permissions:
      contents: read
    uses: ./.github/workflows/validate.yml

  release:
    needs:
      - ci
      - validate
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
      packages: write

    steps:
      - uses: actions/checkout@v7

      - name: Publish Features
        uses: devcontainers/action@v1
        with:
          publish-features: true
          base-path-to-features: ./src
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
